##### Basic #####

# prefix
unbind C-b
set -g prefix C-a
bind C-a send-prefix

# clipboard / passthrough
set -g allow-passthrough all
set -g set-clipboard on


##### Window / Pane hotkeys #####

# split panes
unbind '"'
unbind %

bind-key '\' split-window -v
bind-key '|' split-window -h

# vim-style pane navigation
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R


##### Custom hotkeys #####

# Create new session from current pane path
bind-key S command-prompt -p "session name:" "new-session -s '%%' -c '#{pane_current_path}'"


##### Terminal color #####

set -g default-terminal "tmux-256color"
set-option -ga terminal-overrides ",*:Tc"


##### Platform-specific config #####

if-shell "uname -s | grep -q Darwin" "source ~/.config/tmux/macos.conf"


##### extra config #####
source ~/.config/tmux/exp.conf
source ~/.config/tmux/utility.conf


##### TPM path #####

set-environment -g TMUX_PLUGIN_MANAGER_PATH "$HOME/.config/tmux/plugins/"


##### Plugins #####

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'

# Kanagawa theme
set -g @plugin 'catgoose/kanagawa-tmux'


##### Status bar #####

set -g status-left-length 60
set -g status-right-length 120


run "$HOME/.config/tmux/plugins/tpm/tpm"
